.\" Manpage for sipreport.
.\" Contact pepeluxx@gmail.com to correct errors or typos.
.TH SIPREPORT 1 "13 Jan 2022" "version 2.0.5" "sipreport man page"
.SH NAME
\fBsipreport\fR \- extracts values from sippts.db database

\fBsipreport\fR is part of SIPPTS suite: https://github.com/Pepelux/sippts
.SH SYNOPSIS
nuseradd [USERNAME]
.SH DESCRIPTION
\fBsipreport\fR extracts values from database that have been saves with the SIPPTS tools (sipscan, sipexten, sipcracker).
.SH OPTIONS
.PP
\fB\-h \fR\fIhost\fR
.RS 4
Filter using a hostname or IP address.
.RE
.PP
\fB\-noexten \fR
.RS 4
Show only servers and devices (not extensions nor users).
.RE
.PP
\fB\-noauth \fR
.RS 4
Show extensions where authentication is not required.
.RE
.PP
\fB\-version \fR
.RS 4
Shows running version.
.RE
.SH BUGS
No known bugs.
.SH AUTHOR
Jose Luis Verdeguer (pepeluxx@gmail.com)