.\" Manpage for sipspy.
.\" Contact pepeluxx@gmail.com to correct errors or typos.
.TH SIPSPY 1 "13 Jan 2022" "version 2.0.5" "sipspy man page"
.SH NAME
\fBsipspy\fR \- is part of SIPPTS suite: https://github.com/Pepelux/sippts
.SH SYNOPSIS
nuseradd [USERNAME]
.SH DESCRIPTION
\fBsipspy\fR is a fake SIP server that listens on port 5060/UDP and responds to REGISTER message authentication requests.

The purpose of sipspy is to obtain the digest authentication response from a device that thinks it is connecting to a PBX server:

Device                                      Fake SIP Server
         ---> REGISTER (with no auth) ---> 
         <--- 401 Unauthorized        <---
         ---> REGISTER (with auth)    ---> 
.SH OPTIONS
.PP
\fB\-h \fR
.RS 4
Show help.
.RE
.PP
\fB\-p \fR\fIport\fR
.RS 4
Specifies a local port number. If not specified, the sip port (5060) is used.
.RE
.PP
\fB\-v \fR
.RS 4
Verbose mode (trace information).
.RE
.SH BUGS
No known bugs.
.SH AUTHOR
Jose Luis Verdeguer (pepeluxx@gmail.com)